### ISSUE TITLE
Fails for notebooks with spaces in filename

### ISSUE THREAD

**Issue by goerz** [goerz/jupytext.vim#1]
A notebook with spaces in the filename results in an empty buffer

**Comment by goerz** [comment]
@mwouts Can you confirm this working? BTW, are you on Windows or Linux/Mac? I'm not sure the plugin works on Windows due to the use of a slash as a path separator, but I don't really have access to a Windows system to test this.

**Comment by mwouts** [comment]
Hello @goerz , I confirm this works on Linux, at least on my Ubuntu installed as the bash interpretor for Windows 10. I have also tested on vim81 for Windows, and the plugin worked for notebooks with no spaces in the name, but not when there was a space. The error occured only when updating the notebook on exiting vim:
```
Erreur détectée en traitant function <SNR>10_write_to_ipynb :
ligne   11 :
!jupytext --from=md --to=ipynb --output=C:\Users\Marc\Documents\Notebook\ renamed.ipynb --update "C:\Users\Marc\Document
s\Notebook renamed.md": 2
```
