### ISSUE TITLE
Auto-reload current file in Jupyter Notebook?

### ISSUE THREAD

**Issue by hejops** [goerz/jupytext.vim#22]
Probably not the best place to ask this question, but I'm quite new to Jupyter Notebook, so I'll give it a try. I do all my notebook editing in vim through this plugin, but any changes made are not reflected in Jupyter Notebook until a manual reload is done in JN; I can verify that both the .ipynb and .py files have changed on disk. Is there any way to automatically trigger a reload of the .ipynb file within JN?

I've tried something like [this](https://gist.github.com/deehzee/86ad60d3d2e375013ec710234f88968c), but as far as I can tell it applies to submodules that the current file relies on, and not the current file itself.

**Comment by mwouts** [comment]
Hi @hejops , you don't need `autoreload` here, that is for a different use case (edit your `.py` modules and use them without having to restart your Jupyter Kernel)

What you need here is
- F5 or Ctrl + R (reload the web page) in Jupyter Notebook
- _Reload Notebook From Disk_ in the _File_ menu in Jupyter Lab >= 3.0

**Comment by hejops** [comment]
Thanks. Does vim potentially have any control of a Jupyter server/browser? I was thinking a BufWritePost autocmd could work nicely, but I doubt vim has that kind of control.

**Comment by anuramat** [comment]
jupyterlab with jupyter-collaboration plugin will automatically reload the notebook, keeping the old outputs

**Comment by goerz** [comment]
I would also note that `jupytext.vim` is primarily for when you *don't* have a Jupyter server running, to edit random `.ipynb` files.  If you do have Jupyter running, then it's better to use the actual Jupytext Jupyter-plugin, pair your notebooks, and edit the paired files. You will still need "Reload Notebook From Disk" (or whatever improvements Jupyter will bring to this in the future)

In any case: this would be Jupyter's responsibility, not vim's.

> jupyterlab with jupyter-collaboration plugin will automatically reload the notebook, keeping the old outputs

Unfortunately, Jupytext (the Jupyter-plugin, not this vim plugin) is incompatible with the jupyter-collabortation plugin: https://github.com/jupyterlab/jupyter-collaboration/issues/214
