### ISSUE TITLE
Jupytext lab extension failed to validate 

### ISSUE THREAD

**Issue by gsihaj5** [goerz/jupytext.vim#39]
while editing the md file it work perfect, the ipynb is updated

but i need to close and re open the ipynb file in the jupyter lab page to trigger the update in jupyter lab

after installing fresh jupyter-lab with conda 

and after checking installed lab extension both jupyterlab_jupytext jupytext enabled
but it failed to validate

i think this might the issue causing it won't update the ipynb file 

```
    jupyter_lsp enabled
    - Validating jupyter_lsp...
      jupyter_lsp 2.2.5 ok
    jupyter_server_terminals enabled
    - Validating jupyter_server_terminals...
      jupyter_server_terminals 0.5.3 ok
    jupyterlab enabled
    - Validating jupyterlab...
      jupyterlab 4.2.2 ok
    jupyterlab_jupytext enabled
    - Validating jupyterlab_jupytext...
      jupyterlab_jupytext  ok
    jupytext enabled
    - Validating jupytext...
       X validation failed
    notebook_shim enabled
    - Validating notebook_shim...
      notebook_shim  ok
```

**Comment by goerz** [comment]
This vim plugin has nothing to do with Jupyter Lab. You should probably not be using it if you have Jupyter Lab with the Jupytext extension running. See https://github.com/goerz/jupytext.vim/issues/22

**Comment by gsihaj5** [comment]
Thanks, i just don't know the plugins for this auto refresh. 
it works flawlessly with jupyter-collaboration
